name: dynamic_forms
description: POC for dynamic forms from JSON

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^2.0.1
  # Bloc for state management
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  # Value equality
  equatable: ^0.4.0
  # Functional programming thingies
  dartz: ^0.8.6
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2
  # Local cache
  shared_preferences: ^0.5.3+4
  # overriding hashcode for custom object equality checks
  quiver: ^2.0.5
  # show images from the internet & store them in cache (temp directory)
  cached_network_image: ^2.2.0+1
  # navigation
  get: ^3.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter:
  uses-material-design: true